# HTTP bootstrap. Certbot will add HTTPS and redirect after DNS is ready.
server {
    listen 80;
    listen [::]:80;
    server_name keelek.kuayrai.com;
    server_tokens off;
    client_max_body_size 2m;
    access_log /var/log/nginx/keelek.access.log;
    error_log /var/log/nginx/keelek.error.log;
    location / {
        proxy_pass http://127.0.0.1:8081;
        include /etc/nginx/snippets/platform-proxy.conf;
    }
}
