import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App.jsx";
import "@fontsource/mali/400.css";
import "@fontsource/mali/500.css";
import "@fontsource/mali/600.css";
import "@fontsource/mali/700.css";
import "@fontsource-variable/manrope";
import "./style.css";
import "./theme.css";
import "./dark.css";
createRoot(document.getElementById("root")).render(<App />);
